steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/marketsense-backend:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/marketsense-backend:$SHORT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/marketsense-backend:$SHORT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=.
      - '--image=gcr.io/$PROJECT_ID/marketsense-backend:$SHORT_SHA'
      - '--location=us-central1'
      - '--cluster=run'

  # Step 4: Deploy to Cloud Run directly
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'marketsense-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/marketsense-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'

images:
  - 'gcr.io/$PROJECT_ID/marketsense-backend:latest'
  - 'gcr.io/$PROJECT_ID/marketsense-backend:$SHORT_SHA'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'
